# Generated by Django 2.1.3 on 2019-03-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accname', models.CharField(max_length=255, verbose_name='账户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('identity', models.CharField(max_length=255, verbose_name='身份')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('sex', models.BooleanField(verbose_name='性别')),
                ('first', models.BooleanField(default=0, verbose_name='密码状态')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.Teacher', verbose_name='教师')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名')),
                ('value', models.BinaryField(max_length=65000, verbose_name='值')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='token')),
                ('value', models.BinaryField(max_length=2555, verbose_name='值')),
                ('expiration', models.DateTimeField(verbose_name='过期时间')),
            ],
        ),
    ]
