# Generated by Django 2.1.3 on 2019-03-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='班级编号')),
                ('name', models.CharField(max_length=255, verbose_name='班级名称')),
                ('number', models.IntegerField(verbose_name='班级人数')),
                ('session', models.IntegerField(verbose_name='届')),
                ('academe', models.CharField(max_length=255, verbose_name='学院')),
                ('faculty', models.CharField(max_length=255, verbose_name='系')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='PlanClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='上课人数')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class', verbose_name='班级')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.TeachPlan', verbose_name='教学计划')),
            ],
        ),
    ]
