# Generated by Django 2.1.3 on 2019-03-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='课程编号')),
                ('name', models.CharField(max_length=255, verbose_name='课程名称')),
                ('describe', models.CharField(max_length=255, null=True, verbose_name='课程简述')),
                ('type', models.CharField(max_length=255, verbose_name='课程类型')),
                ('period', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='默认课时(h)')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='TeachPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(verbose_name='学期')),
                ('period', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='课程课时(h)')),
                ('number', models.IntegerField(verbose_name='上课总人数')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseLib', verbose_name='课程')),
            ],
        ),
    ]
