# Generated by Django 2.1.3 on 2019-03-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='教学方式')),
                ('period', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='课程课时(h)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.TeachPlan', verbose_name='教学计划')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('professional_rank', models.CharField(max_length=255, verbose_name='职称')),
                ('phone', models.CharField(max_length=255, verbose_name='联系方式')),
                ('academe', models.CharField(max_length=255, verbose_name='学院')),
                ('faculty', models.CharField(max_length=255, verbose_name='系')),
                ('education', models.CharField(max_length=255, verbose_name='学历')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='planteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.Teacher', verbose_name='教师'),
        ),
    ]
