# Generated by Django 2.1.3 on 2019-03-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='教材类型')),
                ('main', models.BooleanField(verbose_name='是否为主教材')),
            ],
        ),
        migrations.CreateModel(
            name='TeachMaterialLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='教材编号')),
                ('name', models.CharField(max_length=255, verbose_name='教材名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('type', models.CharField(max_length=255, verbose_name='教材类型')),
                ('spec', models.CharField(max_length=255, verbose_name='教材规格')),
                ('pubdate', models.DateField(verbose_name='出版时间')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版社')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='planmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachmaterial.TeachMaterialLib', verbose_name='教材'),
        ),
        migrations.AddField(
            model_name='planmaterial',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.TeachPlan', verbose_name='教学计划'),
        ),
    ]
